### PR TITLE
Extending the EphemeraFolder feature tests for saving and creating subsequent folders

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Ensures that #509 is resolved

### CODE REVIEW

**Comment by jrgriffiniii** [comment]
Please note that this does *not* actually resolve #509, as I could not reproduce this on the `master` branch.  My suspicion is that this was quite recently resolved by https://github.com/pulibrary/figgy/pull/507

**Comment by escowles** [comment]
I just confirmed the problem with Save and Create Another in production just now.  I'm going to deploy the current `master` branch to see if it is resolved.

**Comment by escowles** [comment]
Alas, after doing a deploy to production, I'm still seeing the same error — doing "Save and Create Another" behaves the same as "Save"

**Comment by jrgriffiniii** [comment]
Apologies, I'll need to return to attempting to reproduce this, as I'm getting the following within production:

issues_509_screenshot_prod

**Pull request merged**
