### PR TITLE
Remove unneeded import services and TinyTDS

### LINKED ISSUE #4559: Remove numismatics import service
Import was completed successfully. No longer needed.

### PR DESCRIPTION
**Pull request by eliotjordan**
Removes numismatics import, music import, and TinyTDS. 

Closes #4559

### CODE REVIEW

**Review by tpendragon — DISMISSED** [review]
This is really exciting, thanks!

**Review by hackartisan — CHANGES_REQUESTED** [review]
Yessss! Can you also remove the stuff about FreeTDS from the README?

**Comment by hackartisan** [comment]
Re: test failures, I think that archives-client stuff was resolved yesterday; maybe this just needs to be rebased.

**Comment by eliotjordan** [comment]
@hackartisan Updated the README and the archivesspace client issue should be resolved.

**Review by hackartisan — APPROVED** [review]

**Pull request merged**
