### PR TITLE
updates locales/en.yml to include Letter in Type of Work

### PR DESCRIPTION
**Pull request by christinach**

### CODE REVIEW

**Comment by christinach** [comment]
closes #2918

**Comment by christinach** [comment]
I can see the change locally but not in staging.

**Comment by escowles** [comment]
I'm seeing the error still too — I even restarted Passenger on figgy-staging1 and tried a different browser, with no effect.

**Comment by eliotjordan** [comment]
This works. The resources just needed to be reindexed.

**Pull request merged**
