### PR TITLE
Fix stale object error for vector and raster derivatives

### LINKED ISSUE #3172: Stale object error for resources
## Implementation

Make sure derivative jobs have fresh references to the resource after each save.

Check honeybadger for other instances of this error.

## Backtrace

    line 75 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in save
    line 48 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in trace
    line 44 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/48943330)

---

Stale object errors were fixed for scanned map derivatives (https://github.com/pulibrary/figgy/pull/3136), but not for vector and raster derivatives.

### PR DESCRIPTION
**Pull request by eliotjordan**
Closes #3172

### CODE REVIEW

**Comment by hackmastera** [comment]
This is the one you couldn't work up a test for?

**Comment by eliotjordan** [comment]
@hackmastera This this the one.

**Comment by hackmastera** [comment]
Should we remove the test added in https://github.com/pulibrary/figgy/pull/3136/files since you determined it doesn't work?

**Comment by eliotjordan** [comment]
@hackmastera Removed that test.

**Pull request merged**
