### PR TITLE
Positions check-mark relative and changes color to green

### PR DESCRIPTION
**Pull request by christinach**

### CODE REVIEW

**Comment by christinach** [comment]
closes #1134

**Comment by tpendragon** [comment]
@christinach Can we get a screenshot of what this looks like?

**Comment by christinach** [comment]
@tpendragon  screen shot 2018-05-01 at 7 00 30 pm

**Comment by tpendragon** [comment]
It looks good to me. @escowles Was there a stakeholder who asked about this that we can show the screenshot to?

**Pull request merged**
