### PR TITLE
Adding remote metadata refresh to bulk edit screen

### LINKED ISSUE #5229: Add "Refresh metadata from PULFA/Voyager" to bulk edit functionality
### Summary
As a figgy user, I would like to "Refresh metadata from PULFA/Voyager" via the bulk edit feature in figgy. Sometimes I may hear of changes to the MARC or FA records for multiple items in a collection and manually editing each item would be cumbersome.
This is due to actual use cases:

- EAL #4652 
- Lapidus #5227 
- Middle East Manuscripts (slack communications) -Joyce Bell is doing massive remediation on a subset of Manuscripts from the Islamic World.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This is not hindering work in figgy itself, but it is contributing to outdated/incorrect metadata being displayed to our users in our applications.

### Priority recommendation

- [ ] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

### PR DESCRIPTION
**Pull request by escowles**
Fixes #5229

### CODE REVIEW

**Review by hackartisan — COMMENTED** [review]
Should we be concerned about the Alma api limits? Do we need any guardrails here?

**Comment by escowles** [comment]
Trey and I have talked about that. I think the collection limit is a pretty big guard-rail here (I think the largest collection with Alma remote metadata is the Arabic Microfilm, with 8k items). But I do think it's worth considering if this should be a Rake task instead, or if there are other approaches we can take.

I'm going to mark this is draft until we agree on that, and because I'd like to test this in staging before it's merged.

**Comment by tpendragon** [comment]
@escowles This is unblocked now, if you want to rebase and mark it ready for review.

**Comment by escowles** [comment]
I tested this in staging and it works as intended, with one caveat: if a collection has some items with remote metadata and some items without, the bulk edit will fail when it tries to update remote metadata for the items that don't have it. @kelea99 and I talked about this and agreed it's probably fine because collections typically all have remote metadata or none of them do.

**Review by tpendragon — APPROVED** [review]

**Pull request merged**
