### PR TITLE
Add report for resources with an alma source metadata id but a finding aids ark target

### PR DESCRIPTION
**Pull request by hackartisan**
advances #6343

### CODE REVIEW

**Comment by hackartisan** [comment]
On staging it seems to check the resources like 2 per min, which is gonna take 32 days on prod. Not hitting errors anymore, though -- Maybe it'll run faster on prod? Worth a shot.

**Comment by hackartisan** [comment]
@escowles It seems to take a really long time to check these ark resolutions. Trey said we can maybe get a dump of ezids, and that you maybe know how to get that?

**Comment by hackartisan** [comment]
Okay thanks @escowles! I'll just have to look into why resolving them is so slow via the ezid client, and/or do it some other way.

**Comment by escowles** [comment]
FWIW, the script I used the last time I did this just did a HEAD request to resolve them:

```
#!/bin/sh

# lookup redirect URL for all ARKs in file "arks.txt"

function f
{
  read ARK
  while [ "$ARK" ]; do
    LOC=`curl -s -I https://n2t.net/$ARK | grep Location`
    echo $ARK $LOC
    read ARK
  done
}

cat arks.txt | f
```

**Comment by hackartisan** [comment]
Nice! Ha, my first plan was to do HEAD requests, before I got distracted by the Ezid client gem.

**Review by tpendragon — APPROVED** [review]

**Comment by tpendragon** [comment]
This is great, good work!

**Pull request merged**
