### PR TITLE
Updated members_numismatic_issue UI with data-tables

### PR DESCRIPTION
**Pull request by christinach**

### CODE REVIEW

**Comment by christinach** [comment]
before: 
Screen Shot 2019-05-01 at 3 13 03 PM

**Comment by christinach** [comment]
with the data-tables
Screen Shot 2019-05-01 at 3 14 12 PM
 update:

**Comment by christinach** [comment]
I added a custom width in the thumbnail column so that if there is no thumbnail image the column will not expand based on the coin url content. This way the 'Actions' column will fit both buttons 'view' and 'edit'.

**Comment by christinach** [comment]
I also removed the panel. I think the data-tables view looks cleaner without a panel.

**Comment by christinach** [comment]
closes #2934

**Comment by eliotjordan** [comment]
This looks great. We should do this with all of our child resource partials.

https://github.com/pulibrary/figgy/issues/2962

**Pull request merged**
