### PR TITLE
[WIP] Implements a RemoteChecksumJob and RemoteChecksumService

### PR DESCRIPTION
**Pull request by jrgriffiniii**
This is not complete, but I am interested in clarifying my understanding of #2773 before advancing this.  This would ensure that an original file for a `FileSet` could be uploaded to a Google Cloud Storage Bucket, and have its checksum calculated for any given resource.

Is this a desired pattern?  Or should the job rely upon the ZIP-compressed directory created by the  `BagExporter` as the resource to upload into the cloud?

### CODE REVIEW

**Comment by escowles** [comment]
Yes, I think it's good to check individual files in cloud storage — other than Glacier, I think the APIs are such that we don't need to take the extra step of packaging in zip/tar archives.

I think the workflow will be to create a Bag on local disk, and then push all the files in the Bag to cloud storage, and then to check them individually.  It's probably worth exploring whether the local filesystem is required, or if we could explore generating Bags directly to cloud storage.

**Comment by tpendragon** [comment]
I gotta say, I'm liking the idea of zipping the bags.

**Comment by escowles** [comment]
I have mixed feelings about zipping Bags — on one hand it definitely makes it easier to move them around and provides a nice package for users who work with them.  But it adds a layer of hassle when working with them.

Also, I've had trouble in the past with archive libraries and command-line utilities working consistently with archives greater than a certain size (IIRC, 4GB).  I tested a bunch of different tools and found only Gnu Tar could actually create and read archives bigger than that (other options including Java's Tar/Zip support, InfoZip, and BSD Tar all had serious issues that resulted in unreadable archives). Things may have changed in that area since then (this was 5+ years ago), but I think we should be careful to make sure that anything we do here is going to scale up to our largest objects.

**Comment by tpendragon** [comment]
Sorry, when I say zip I mean .tar.gz, it's a bad habit. I hadn't ever heard of problems with it, especially with such low file sizes! We'll definitely have to triple check that it works.

I like the idea of zipping up the bags because it means we have a single file that we can upload, we can associate that file with the metadata (add it to the file_identifiers for a ScannedResource for instance, or even create a FileMetadata node to store the checksum of that zip file), and we can version the bucket so if we keep the name the same we can keep all copies of it forever. Checksumming could become a single check.

**Comment by jrgriffiniii** [comment]
This PR is still unfinished, but there are a number of approaches I can take moving ahead:

`RemoteBagChecksumJob` now creates and appends a `FileSet` for a Bag.  If the bag should be compressed, it compressed it into a single `FileMetadata` node.  Currently ZIP and TAR compression are supported for these.  For uncompressed Bags, the `FileMetadata` nodes are created for each file in the Bag, and these are stored as members of the Bag FileSet.  The checksums here should be stored at the `FileMetadata` layer.

`RemoteBagFileSetChecksumJob` takes my initial approach, where a FileSet is created for a compressed bag, and the checksum is stored at the `Resource` layer.  For uncompressed Bags, each Bag item has a FileSet created, and the checksum is stored on each FileSet (at the `FileSet` layer).

I'm still uncertain as to whether or not compression should be supported, and where best to persist the checksum information (my suspicion is that using the `FileMetadata` would be best).  I can continue to clean this code and improve the tests until this is determined.

**Comment by escowles** [comment]
@jrgriffiniii Let's talk about this on Monday.  I was envisioning two independent processes:
1. When an object with a preservation policy set is created or updated, Figgy spawns a job that Bags the object and persists the Bag to cloud storage.  (#911 / #2554)
2. A GCE instance constantly chooses a random Bag, verifies it, repeating ad infinitum (#2773). These two processes definitely depend on each other, because they need to agree on what the Bags look like, where they are, and how to find them.  But I wasn't thinking that the audit service would create the Bags, just check the ones that already exist.

**Comment by jrgriffiniii** [comment]
> These two processes definitely depend on each other, because they need to agree on what the Bags look like, where they are, and how to find them.

My understanding is that Bags are either directories or compressed files.  The preference seemed to have been for directories, but I don't recall what the final determination was given https://github.com/pulibrary/figgy/pull/2781#issuecomment-477284246

I can tailor this PR to address either case.

As for storing and finding the Bags, I'm simply delegating to the `BagExporter` here: https://github.com/pulibrary/figgy/pull/2781/files#diff-90141f9e31e7124f30bef4f6ba255f22R104

From what I could best determine, this does not provide any approach to compression (if that is desired).

> But I wasn't thinking that the audit service would create the Bags, just check the ones that already exist.

I can adjust this in the PR, https://github.com/pulibrary/figgy/pull/2781/files#diff-90141f9e31e7124f30bef4f6ba255f22R15 does create the `FileMetadata` nodes on a `FileSet` if they don't exist, and that can be removed.

**Comment by jrgriffiniii** [comment]
A strategy for using a separate, cloud-based service is going to be tested as an alternative to the approach proposed in this PR.

**Pull request closed without merging**
