### PR TITLE
Add new SimpleResource model for use with Plates collection

### LINKED ISSUE #1026: Create Bookplate model

### PR DESCRIPTION
**Pull request by hackmastera**
To that end, does a bit of refactoring in decorators and extracts shared specs from scanned_resource specs in models, change_sets, controllers, and decorators.

fixes #1026

### CODE REVIEW

**Comment by hackmastera** [comment]
note this is a reordering of work done originally in #1038; the commits have been organized so that the one adding the model is last, and can be used as documentation of the current process of adding a new model in light of the extracted specs. More work could have been done to make the other commits cleaner, but that didn't seem as important.

**Comment by escowles** [comment]
@hackmastera Can you squash 60f72a2887a6c6622e3385073edfbb785fd6ddd0 into 4249f9a3ade7c2242f16f5c3843f4f14b215b1b3 (removing the temporary Valkyrie/Valhalla renaming)?

**Comment by hackmastera** [comment]
@escowles hey I thought there was a commit between the two complicating that option; maybe there was at one point. thanks for catching this.

**Comment by hackmastera** [comment]
the commits are now showing in a weird order here. they look right for me locally, not sure what is going on.

**Comment by hackmastera** [comment]
The pr is displaying commits in order of creation date instead of git/DAG order. the correct order is:

ffdf336 Refactoring the Decorators by permitting .display and .suppress to ta…
e570162 Introduces shared specs for the Models, ChangeSets, and Decorators
f672cec Fix scanned resource specs
7b630a7 Extract scanned_resources controller specs into a shared spec
e549747 Implementing the SimpleResource Model, ChangeSet, and Decorator; Modi…

**Comment by escowles** [comment]
Closing in favor of https://github.com/pulibrary/figgy/pull/1045

**Pull request closed without merging**
