### PR TITLE
Install/Configure Blacklight Range limit

### LINKED ISSUE #4254: Add a date facet to Figgy
The VIrtual Reading Room (VRR) [functional requirement](https://docs.google.com/spreadsheets/d/1z8Z_k42inQtAHarRrOfjMGzSwnYoCpIOr0J99RL6kqk/edit#gid=0) R006 that "components be searchable by component name, collection name, date, etc."

This metadata should currently be in the index, however to meet this requirement, it's been requested that we add a date facet to Figgy's search interface. 

## Implementation Details

* Use the "created" field for this facet.
* If possible, implement this facet with a slider (such as the [blacklight_range_limit plugin](https://github.com/projectblacklight/blacklight_range_limit)).
* This facet will just pull in the value of the start date, where there is otherwise a date range.

### PR DESCRIPTION
**Pull request by tpendragon**
This adds a date facet.

Closes #4254.

### CODE REVIEW

**Review by hackmastera — CHANGES_REQUESTED** [review]
This looks good.

There are 2 complications:

1. Looks like there's a test that needs to be adjusted.
1. I found a bug in the indexer for which I opened https://github.com/pulibrary/figgy/pull/4262. I opened it against this branch, let me know if you'd rather merge this separately and I can change the base of that PR.

Otherwise I tried it on my dev instance and it works as expected. Thank you!

**Comment by hackmastera** [comment]
Oh also! A release note seems relevant here.

**Comment by tpendragon** [comment]
@hackmastera Should be ready to look at.

**Review by hackmastera — CHANGES_REQUESTED** [review]
Almost there! rubocop is angry.

**Review by hackmastera — CHANGES_REQUESTED** [review]
Apparently we need a test for `app/controllers/search_history_controller.rb`

**Comment by hackmastera** [comment]
oh, looks like you already saw that!

**Review by hackmastera — APPROVED** [review]

**Pull request merged**
