### PR TITLE
Update directions for a fresh install.

### PR DESCRIPTION
**Pull request by tpendragon**
I just set up Figgy on a fresh MacOS box with asdf, so I thought
scripting the commands together would make it easier.

### CODE REVIEW

**Review by hackartisan — COMMENTED** [review]
This is cool!

I think it would be good to adjust the dependencies sections to make it clear what steps can be replaced by running this script. I can take a pass at it and add a commit for consideration.

**Comment by hackartisan** [comment]
@tpendragon what do you think of my changes?

Note that I removed ubuntu instructions since they were incomplete and I don't think we have anyone using them. Also I figured we have them in the ansible codebase.

**Comment by tpendragon** [comment]
I like it!

**Comment by tpendragon** [comment]
I approve of your commit, but I can't approve this PR @hackartisan if you could.

**Review by hackartisan — APPROVED** [review]

**Pull request merged**
