### PR TITLE
2096 create playlist button

### PR DESCRIPTION
**Pull request by christinach**

### CODE REVIEW

**Comment by hackmastera** [comment]
@christinach in future PRs can you put something like "resolves #2096" in the description? Then it will close the ticket automatically when the PR is merged. here is the github documentation https://help.github.com/articles/closing-issues-using-keywords/

**Comment by christinach** [comment]
I will do, thanks. Usually I put `closes and the number'. I missed this one.

**Comment by hackmastera** [comment]
👍 sorry to overexplain.

the only reason i could think that it might not work is that you have to make sure to include the `#` before the number. Oh, also it doesn't work if you put it in the title -- for a long time i had to keep moving it from title to description because i kept doing it wrong 😁

**Comment by christinach** [comment]
I don't know whats the case but I do include the `#`.

**Pull request merged**
