### PR TITLE
Removing unique constraint on user email field

### LINKED ISSUE #460: Guest users for Figgy can't search
https://app.honeybadger.io/projects/53391/faults/35095579#notice-summary

### PR DESCRIPTION
**Pull request by escowles**
Fixes #460

### CODE REVIEW

**Comment by tampakis** [comment]
Yay guest users can search now!

**Comment by hackmastera** [comment]
@escowles I'm confused; are there not side effects of this change for registered user accounts?

**Comment by escowles** [comment]
@hackmastera This change brings the index in line with the column definition: the email field wasn't declared unique (which is why AR can create multiple users with the same (empty) email), but then the unique constraint on the index would result in an error.

**Comment by hackmastera** [comment]
@escowles thanks for the clarification!!

**Pull request merged**
