### PR TITLE
Ephemera preservation

### LINKED ISSUE #3454: EphemeraFolder/EphemeraProject/EphemeraBox should preserve.
When a box is marked "all complete" it should preserve all of its folders.

When a box is marked "all complete" it should preserve.

When a folder is marked complete, it should preserve.

A project should preserve immediately. They don't have states.

### LINKED ISSUE #3456: Preserve EphemeraVocabulary/Term
Their ChangeSets are inheriting from `Valkyrie::ChangeSet`

## Success Criteria

They're preserved as metadata.json files.

### PR DESCRIPTION
**Pull request by eliotjordan**
- Test EphemeraBox and EphemeraFolder preservation
- Ensure EphemeraVocabulary and EphemeraTerm resources preserve

Closes #3454
Closes #3456

### CODE REVIEW

**Review by tpendragon — CHANGES_REQUESTED** [review]
This code's great. I'm blocking on this question:

What happens if I add a folder to a box that's marked all_in_production? Does it preserve? Am I motivated to mark it complete so it will?

**Comment by eliotjordan** [comment]
@tpendragon If you add a folder, it won't preserve until it's marked "complete", no matter the state of the parent box. Feels OK to me to only trigger preservation on a Folder once it's marked complete, but I may not know the use cases.

**Comment by tpendragon** [comment]
@eliotjordan If I add a folder to an all_in_production box does it behave as if it's complete or nah?

**Comment by eliotjordan** [comment]
@tpendragon It does not.

**Review by tpendragon — APPROVED** [review]

**Pull request merged**
