### PR TITLE
Try out new select for Ephemera.

### PR DESCRIPTION
**Pull request by tpendragon**

### CODE REVIEW

**Review by hackartisan — CHANGES_REQUESTED** [review]
It's a bit tight at the top when the dropdown appears. It looks like we can add a padding-top on the `.select2-results__options`

**Comment by tpendragon** [comment]
@hackartisan Can you screen shot what you mean by tight at the top?

**Comment by hackartisan** [comment]
Screen Shot 2022-07-08 at 3 17 23 PM

**Comment by tpendragon** [comment]
Uh, weird, I don't think that's how it looks to me.

**Comment by hackartisan** [comment]
@tpendragon It looks like the issue is that it opens up already scrolled to the bottom. can you replicate that on this object? https://figgy-staging.princeton.edu/concern/ephemera_folders/040473cf-c141-4be9-b7f6-58ffd947df59/edit

**Comment by tpendragon** [comment]
Yup, weird, doesn't seem to be the case for new items.

**Comment by hackartisan** [comment]
It's still better than without this fix. I won't block on it if you want to ticket and mergre.

**Comment by tpendragon** [comment]
I think this broke Numismatics, per @eliotjordan 

```
Unforunately, it seems to have broken Issue and Coin forms. See Metal, Shape, Color: https://figgy-staging.princeton.edu/concern/numismatics/issues/new
```

**Comment by tpendragon** [comment]
This wasn't what broke numismatics, but I had to enable lux for all the Ajax-Select'y fields to get this to work.

**Review by eliotjordan — APPROVED** [review]

**Comment by tpendragon** [comment]
Created https://github.com/pulibrary/figgy/issues/5234

**Pull request merged**
