### PR TITLE
Increase space between save and delete buttons

### LINKED ISSUE #2456: Ephemera: Delete button is too close to other buttons
Separate delete buttons from other buttons to avoid accidentally clicking them

### PR DESCRIPTION
**Pull request by escowles**
Fixes #2456

### CODE REVIEW

**Comment by christinach** [comment]
@escowles do we have a `confirm message` when the user clicks the delete button?

**Comment by escowles** [comment]
@christinach Yes, but Gabrielle said it was annoying to have it so close, since she accidentally clicked it a few times, and was often worried about clicking it.

**Comment by tpendragon** [comment]
I think we should deploy this to staging and show it to Gabrielle, because to me it doesn't seem like this'd fix the issue

**Comment by escowles** [comment]
I've deployed my branch to staging and emailed Gabrielle to ask her if the update helps.

**Pull request merged**
