### PR TITLE
Remove Voyager ID Support

### LINKED ISSUE #4977: Convert Voyager fixtures to Alma fixtures.
To convert specs to use Alma IDs:
- [ ] Increase the limit in https://github.com/pulibrary/figgy/blob/54956c614ef827d1de6a6f781e96677b231672ad/app/services/pul_metadata_services/client.rb#L38-L42
- [ ] Run the suite to find and fix failures, be mindful of places where conversation from old to new IDs may be happening. An example of handling that situation is https://github.com/pulibrary/figgy/pull/5706/files#diff-0761751d54566c63faed78a855cd752748f6204eff9aa290466b73fd8ed02c5eR262

Question: Do actual new fixtures need to be pulled?

### LINKED ISSUE #6270: Bug in new code added for video
## Backtrace

    line 15 of [PROJECT_ROOT]/app/change_sets/change_set.rb: for
    line 123 of [PROJECT_ROOT]/app/services/bulk_ingest_service.rb: attach_children
    line 114 of [PROJECT_ROOT]/app/services/bulk_ingest_service.rb: block in attach_children

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/105736431)

### PR DESCRIPTION
**Pull request by tpendragon**
We haven't had Voyager IDs for a very long time, it's time to finish up removing it.

Closes #6270 
Closes #4977

### CODE REVIEW

**Review by hackartisan — COMMENTED** [review]
How do we know there are no more voyager IDs in staging / production?

**Comment by tpendragon** [comment]
> How do we know there are no more voyager IDs in staging / production?

We ran a migrator that changed 'em all?

**Comment by tpendragon** [comment]
There are no Alma IDs:

```
figgy_production=# select metadata->'source_metadata_identifier'->>0 FROM orm_resources WHERE metadata @> '{"source_metadata_identifier": []}' AND metadata->'source_metadata_identifier'->>0 NOT LIKE '99%' AND metadata->'source_metadata_identifier'->>0 NOT LIKE '%_%';
 ?column?
----------
(0 rows)
```

**Review by hackartisan — CHANGES_REQUESTED** [review]
It looks good, can we verify that we don't have any more voyager IDs in figgy? Or I guess what would happen if we did still have some, they would simply fail to fetch metadata and have to be manually updated?

**Comment by hackartisan** [comment]
Oh great thanks!

**Review by hackartisan — APPROVED** [review]

**Pull request merged**
