### PR TITLE
Disable all Track detach buttons when one is clicked

### LINKED ISSUE #2528: Disable "detach" buttons after you click them in the Playlist members view.
Stops folks from accidentally removing multiple items with no feedback.

### PR DESCRIPTION
**Pull request by hackmastera**
closes #2528

### CODE REVIEW

**Comment by hackmastera** [comment]
screen shot 2019-02-05 at 1 10 11 pm

**Comment by christinach** [comment]
why are we disabling all the Detach buttons and not only the one which is detached?

**Comment by hackmastera** [comment]
@christinach the whole page reloads when you click a button. it's not really intended to support multiple detach actions at once.

**Comment by christinach** [comment]
I understand. Thank you @hackmastera . Maybe this is something that we can improve. -> not loading the whole page when detaching.

**Comment by hackmastera** [comment]
@christinach for example, I just tried it with just disabling the one I click. I was able to click 3 buttons before the page reloaded, and see them all spin, but then when the reload came through, 2 of those had been removed and the 3rd was still there.

**Pull request merged**
