### PR TITLE
[WIP] Deprecates form field partials in favor of markup generation helper methods

### LINKED ISSUE #893: EphemeraFolders#new is really slow.
https://app.datadoghq.com/apm/resource/figgy/rack.request/61226659ce70a726?end=1520887462115&env=none&graphType=span_list&hostGroup=&paused=false&spanID=1920750845366204526&start=1520883862115&traceID=7503113738104096014 is the trace. It's taking something like six seconds to load if you pass a parent_id.

URL: https://figgy.princeton.edu/concern/ephemera_folders/new?parent_id=4e273772-c658-4feb-8021-4bbf7cd8e1d2

Traces say the slowness isn't from database stuff.

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #893

### CODE REVIEW

**Comment by jrgriffiniii** [comment]
@tpendragon the performance issues aren't too terrible on the staging environment, but there is a slight, noticeable improvement.  Using the Chrome DevTools, I've found that `master` requires an average of 155.3ms for the raw server-side response, while this branch averaged at 139.2ms.

For reference, the current `master` on production averages at 1.27s.

**Comment by tpendragon** [comment]
It's weird there's such a big difference...

**Comment by tpendragon** [comment]
Maybe we should deploy this branch to prod and check the timings?

**Comment by escowles** [comment]
👍 testing this with production data seems like a good next step to figure out if this addresses the performance issues.

**Comment by jrgriffiniii** [comment]
After testing this within the production environment, this was not found to significantly improve performance.

**Pull request closed without merging**
