### PR TITLE
Adds a fallback of Arial to the UV theme.

### LINKED ISSUE #928: Unicode/UTF-8 characters are lost in manifest
See:
https://figgy.princeton.edu/concern/scanned_resources/fb1f4cf0-9acb-4c3e-a32e-c2380b11b7ad/manifest

And:
https://catalog.princeton.edu/catalog/4843238#view

### PR DESCRIPTION
**Pull request by tpendragon**
I should probably create a custom theme instead of this, but I can't
figure it out and all the documentation is gone since V3.

Closes #928

### CODE REVIEW

**Comment by escowles** [comment]
I'm still seeing the broken text in Chrome when I deploy this branch to staging: https://figgy-staging.princeton.edu/catalog/fbb62975-c694-4b5c-b01d-709750ee4d79

screen shot 2019-01-05 at 6 43 14 am

**Comment by tpendragon** [comment]
Ha, weird, it worked for me locally. Oh well.

**Comment by tpendragon** [comment]
@escowles It works for me. Maybe you need to force refresh?

**Comment by escowles** [comment]
Weird — I did a force refresh, but it was still broken.  I just tried in a private window, and saw the updated, working title in the viewer.

**Pull request merged**
