### PR TITLE
Remove resource from all collections when it's made a child

### LINKED ISSUE #5678: Remove Collections from any/all child records when child is moved to a parent record in figgy.
### Summary
If collections are not removed from scanned resources that become title-only children of a parent record, those children are pulled in as individual scanned resources to DPUL exhibits. Which is totes bad. 

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
This is not hindering or stopping work. Rather, it is making DPUL exhibits messy and confusing (like Lapidus).
### Priority recommendation

- [x] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
This is a "make developers lives easier" ticket.  Collections  cannot be removed from child records by figgy users. developers are required for that task.  there is likely a lot of cleanup needed for child records that were added to parents after ingest as scanned resources. 

We're making this ASAP because if this happens post-cleanup we've recently done then it'll undo the time we spent to do that cleanup.

### PR DESCRIPTION
**Pull request by hackartisan**
I wanted to add this logic into the existing `AppendToParent` class, but that's used as a post save hook and this needed to be pre-save. I'm not in love with the way this mirrors the logic in that class, and how the two may need to be changed together. Open to other ideas / approaches.

closes #5678

### CODE REVIEW

**Comment by tpendragon** [comment]
Oh interesting, so to put this in one place we'd almost need an around hook or hooks that can have both a pre-save and a post-save method?

**Comment by hackartisan** [comment]
@tpendragon do you think it's appropriate to move it all to pre-save?

Yeah the wrap around idea is interesting..

**Comment by tpendragon** [comment]
I don't think you can append to parent pre-save because you don't have an ID

**Comment by hackartisan** [comment]
aha, for a new resource, that makes sense.

**Comment by kelea99** [comment]
> I don't think you can append to parent pre-save because you don't have an ID

This could perhaps be solved with a workflow change. saving the parent record first before appending the child/children to the parent record? Then an id would be there. 
the soon-to-be child records that are being appended to an existing parent (with ID) are taken care of already.  Does this help at all?

**Comment by hackartisan** [comment]
@kelea99 the scenario where there isn't an id is when the child is new, e.g. the "attach a scanned resource" button on a resource show page, which takes you to a new resource form.

**Comment by hackartisan** [comment]
@tpendragon what do you think of this?

**Comment by tpendragon** [comment]
Looks great to me!

**Review by tpendragon — APPROVED** [review]

**Review by tpendragon — APPROVED** [review]

**Pull request merged**
