### PR TITLE
Add Automatic CDL Ingester

### PR DESCRIPTION
**Pull request by tpendragon**
Work towards #4133 

Ansible PR: https://github.com/pulibrary/princeton_ansible/pull/1663

### CODE REVIEW

**Comment by hackmastera** [comment]
Reviewing:

in spec/resources/cdl/automatic_ingester_spec.rb:12, shouldn't the code be doing this? It doesn't seem like it should be part of test setup. Line 18 is testing that this happened.

One general question. A file goes into the `cdl_in_path` and is moved to `cdl_in_path/ingesting` and then ingested via move from there. If the file is corrupted during these moves it seems like we lose the file entirely and it has to be re-scanned to be reingested -- is that correct? Is there some other guard against this?

**Comment by tpendragon** [comment]
Line 12 is an extra file to make sure it doesn't reingest files that are currently ingesting by a job which is either running or in the retry queue. I'll add a comment. 

We've never really had a problem with file system copies that I can think of. I can adjust it so that it doesn't remove the file until after the ingest is done if that makes you more comfortable?

**Comment by hackmastera** [comment]
In that case on line 12, can you use a different filename.

We have definitely had problems that show up during derivative generation and aren't really caught until much later. I'm not sure but I think sometimes the studio has found those files and they looked fine so they just ingested them again. That's the scenario I'm thinking of.

**Comment by tpendragon** [comment]
I just realized I forgot to get this to add it to a collection anyways. After I do that maybe we can chat about this on zoom?

**Comment by hackmastera** [comment]
Do you think this should get a release note?

Regardless, :thumbsup: approved

**Comment by tpendragon** [comment]
I think the release note should be for when the whole feature's done, personally.

**Pull request merged**
