### PR TITLE
fixes the button spacing issue for numismatics

### LINKED ISSUE #6481: Numismatics Issue and Coin forms have bad button spacing
The Issue and Coin edit and new forms have bad button spacing.

Screenshot 2024-08-23 at 3 00 19 PM
Screenshot 2024-08-23 at 2 59 52 PM

## Acceptance Criteria

- [x] The buttons have standard spacing on forms such as https://figgy-staging.princeton.edu/concern/numismatics/coins/928dfea6-22ff-4282-8316-3f96efdb2d82/edit.

## First Step

- Figure out where those styles are and why they're not spaced like they are in the other forms. Maybe use the chrome inspector and compare this form with the scanned resource edit form.

### PR DESCRIPTION
**Pull request by Seanwarren77**
closes #6481

### CODE REVIEW

**Review by hackartisan — CHANGES_REQUESTED** [review]
Can you please include screenshots similar to the ones in the issue, showing how it looks after applying this fix?

**Comment by Seanwarren77** [comment]
Screenshot 2024-09-17 at 10 58 07 AM

**Comment by hackartisan** [comment]
It doesn't look quite right just yet. I think we should add a wrapper div with the class `admin-controls` around all the buttons.

Here's how it looks in firefox on staging

e.g. https://figgy-staging.princeton.edu/concern/numismatics/coins/928dfea6-22ff-4282-8316-3f96efdb2d82/edit:
Screenshot 2024-09-17 at 3 06 04 PM


the edit issue screen has the same problem as above.

**Comment by Seanwarren77** [comment]
Took your advice and added admin-controls to the button wrapper, looks good to me please look at screen shot.

**Review by eliotjordan — APPROVED** [review]
Looks good. 👍

**Review by hackartisan — APPROVED** [review]

**Pull request merged**
