### PR TITLE
Add ARK report to all collections

### LINKED ISSUE #1977: Enable ark report view to load when a resource is missing an identifier
## Backtrace

    line 16 of [PROJECT_ROOT]/app/views/archival_media_collections/ark_report.html.erb: block in _app_views_archival_media_collections_ark_report_html_erb___4379890785205312006_58641980
    line 14 of [PROJECT_ROOT]/app/views/archival_media_collections/ark_report.html.erb: each
    line 14 of [PROJECT_ROOT]/app/views/archival_media_collections/ark_report.html.erb: _app_views_archival_media_collections_ark_report_html_erb___4379890785205312006_58641980

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/38125355)

```
ActionView::Template::Error: undefined method `first' for nil:NilClass
 ark_report.html.erb  16 block in _app_views_archival_media_collections_ark_report_html_erb(...)
[PROJECT_ROOT]/app/views/archival_media_collections/ark_report.html.erb:16:in `block in _app_views_archival_media_collections_ark_report_html_erb'
14     <% @resources.each do |r| %>
15       <tr>
16         <td><%= r.identifier.first %></td>
17         <td><%= r.source_metadata_identifier.first %></td>
18       </tr>
```

### LINKED ISSUE #2338: New report: source metadata identifiers and Figgy manifest URLs for a collection
After bulk-completing a collection (see #697), the next obvious step is to add the Figgy object URLs to the source metadata (MARC or EAD).  Provide a report where a user can select a collection and get a report of object's source_metadata_identifier, ARK, and Figgy manifest URLs.

### PR DESCRIPTION
**Pull request by hackmastera**
fixes #2338 
also fixes #1977

### CODE REVIEW

**Comment by escowles** [comment]
This looks good — but there are two small changes I think would improve this:
* The manifest paths should be URLs.
* I'm not sure "ARK report" is the best label — maybe "Digital content inventory" or something like that?  I think the focus is on the manifest URLs for populating in the cataloging systems, not the ARK identifiers.

**Comment by hackmastera** [comment]
@escowles thanks for that feedback.

I wonder if even more than the manifest url they will want the full url to a figgy viewer for the object.

**Comment by escowles** [comment]
I believe the finding aids include the manifest URL, and PULFA builds the viewer based on that.  MARC records include the ARK URL, though the viewer is built based on querying Figgy.

**Comment by hackmastera** [comment]
okay i updated to give manifest URL instead of path. user feedback suggests we should stick with "ARK report" for now. otherwise it's green and ready for review.

**Pull request merged**
