### PR TITLE
Refactor manifest builder, fixes #311

### LINKED ISSUE #311: Use iiif_manifest metadata method instead of our override
They added the feature recently.

### PR DESCRIPTION
**Pull request by hackmastera**

### CODE REVIEW

**Comment by hackmastera** [comment]
I'm not sure about my change to `child_record_property_builder.rb` here. If it's required, there's no test checking for it because the specs pass whether I include the metadata or not. Insight on whether to remove it or write a test?

**Comment by hackmastera** [comment]
i'm gonna assume we want metadata there and add a test.

**Comment by escowles** [comment]
@hackmastera I think that's a safe assumption, but I'm honestly not sure.

**Comment by hackmastera** [comment]
@escowles okay! if you're not sure I'll try the test on master first. thanks!

**Comment by hackmastera** [comment]
huh, looks like it's nil on master. I'll back this out.

**Comment by hackmastera** [comment]
that's done and this is ready for review.

**Pull request merged**
