### PR TITLE
Don't raise after a bulk update notification.

### LINKED ISSUE #5116: Don't retry a bulk update after sending email notification
We want to swallow the error so the job doesn't retry, error again, and spam the user.

### PR DESCRIPTION
**Pull request by hackartisan**
Raising means the job re-runs and sends another email.
closes #5116

### CODE REVIEW

**Comment by hackartisan** [comment]
I added the rubocop disable because I think at some point we may want to accumulate all errors and send them in a single email. if/when we do that we won't need the return anymore.

**Comment by hackartisan** [comment]
Make bulk update a database object?

**Comment by tpendragon** [comment]
Or manually requeue with an `alerted:` flag? I'm open to retrying not being useful at all here though, I just realized it'd only happen if something didn't validate.

**Comment by hackartisan** [comment]
It's already passing around a lot of arguments.

**Comment by hackartisan** [comment]
Yeah I don't know that there's a scenario where a retry succeeds without intervention. And if the person intervenes and then starts up the bulk update job again we still have the other one retrying repeatedly.

**Review by tpendragon — APPROVED** [review]

**Comment by tpendragon** [comment]
Works for me.

**Pull request merged**
