### PR TITLE
Reorganize Models

### PR DESCRIPTION
**Pull request by tpendragon**
Wondering if it would make our lives any easier if all the models/change_sets/decorators/wayfinder/controllers for a resource were in the same directory. Looks like this:

screen shot 2018-11-06 at 3 01 20 pm

### CODE REVIEW

**Comment by hackmastera** [comment]
I like it. didn't we have an issue for trying this? I can't find it though.

**Comment by tpendragon** [comment]
Still need to move specs and fix rubocop. :(

**Comment by tpendragon** [comment]
Rubocops done. I propose we merge this to avoid rebasing non-stop and fix the specs in another PR.

**Comment by escowles** [comment]
I've created https://github.com/pulibrary/figgy/issues/2170 for reorganizing the specs.

**Pull request merged**
