### PR TITLE
Add a logical_order setter to scanned resource change set

### LINKED ISSUE #5407: Can't load structure manager on a resource
Resource: https://figgy.princeton.edu/catalog/cfa08806-5a73-4920-9bcc-2c9df295dd38

```
NoMethodError: undefined method `thumbnail_id' for nil:NilClass
```

## Backtrace

    line 71 of [PROJECT_ROOT]/app/helpers/thumbnail_helper.rb: iiif_thumbnail_path
    line 26 of [PROJECT_ROOT]/app/helpers/thumbnail_helper.rb: figgy_thumbnail_path
    line 24 of [PROJECT_ROOT]/app/views/base/_structure_node.html.erb: block (2 levels) in _app_views_base__structure_node_html_erb__2068060152399724350_4539460

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/87791509)

### PR DESCRIPTION
**Pull request by hackartisan**
The new setter filters out structure nodes that try to proxy resources
that don't exist
closes #5407

### CODE REVIEW

**Review by eliotjordan — APPROVED** [review]
Looks great. 👍

**Comment by tpendragon** [comment]
Is there a way to do it by ID? I only ask because grabbing all the children might be expensive for really big objects.

**Comment by hackartisan** [comment]
@tpendragon Hm. Like maybe check to see if the proxy id is in the members list?

**Comment by hackartisan** [comment]
I agree I had the same concern about getting the actual children.

**Review by tpendragon — APPROVED** [review]

**Pull request merged**
