### PR TITLE
Display fixity status on resources

### LINKED ISSUE #3023: Display local and cloud fixity on show pages
When I view an object's show page, I should see a summary of local and cloud fixity checking status and dates checked.  Something like:

## Fixity
* Local: All Files OK, oldest check 03/21/2019
* Cloud: Not checked

### PR DESCRIPTION
**Pull request by escowles**
Fixes #3023

### CODE REVIEW

**Comment by escowles** [comment]
MVWs show cloud and local fixity in the volume list:
fixity1

Scanned Resources show cloud and local fixity at the bottom of the attributes table:
fixity2

FileSets show cloud fixity (which is per-FileSet) at the bottom of the attributes table, and local fixity (which in theory is per-File) in the downloads table):
fixity3

**Comment by escowles** [comment]
ScannedMaps, RasterResources, and VectorResources display fixity like ScannedResources do.  MapSets and other items with child resources don't display fixity — though I'll defer to @eliotjordan whether we should add that, since I haven't heard any requests for fixity display in Geo resources and the members displays are already a little crowded.

**Comment by escowles** [comment]
Numismatics and Ephemera don't display fixity until you get to the FileSet.

**Comment by eliotjordan** [comment]
Not showing fixity status in MapSets is fine. If someone requests that functionality, we can always add it later.

**Comment by escowles** [comment]
The performance on this is quite bad for ScannedResource show pages — about 10 additional seconds for a book with 1500 pages.  I haven't been able to work out the Postgres/JSON syntax, but I think a query like this should be able to retrieve the count of different FileSet fixity statuses much more efficiently:

```
select count(*), metadata->'file_metadata'->'fixity_success' as fixity_success,
from orm_resources where id in (
  select metadata->'member_ids'->'id' from orm_resources where id = '$ScannedResourceID'
) group by fixity_success;
```

The cloud fixity will be several levels more complicated, because the intervening PreservationObject and Event classes, but the same basic strategy should work there too.

**Comment by escowles** [comment]
Got the local fixity query working:
```
figgy_staging=# select tmp.id, tmp.fixity_success from (
figgy_staging(#   select cast(id as text),
figgy_staging(#          jsonb_array_elements(metadata->'file_metadata')->'fixity_success' as fixity_success
figgy_staging(#   from orm_resources
figgy_staging(# ) as tmp
figgy_staging-# where tmp.id in (
figgy_staging(#   select jsonb_array_elements(metadata->'member_ids')->>'id'
figgy_staging(#   from orm_resources where id = 'da7d694f-08fe-4cdd-b263-781c06006e22'
figgy_staging(# );
Time: 926.820 ms
```

**Comment by escowles** [comment]
The basic strategy for retrieving cloud fixity status is:

```
select file_set.id, event.status
from event, preservation_object, file_set
where
  event.resource_id = preservation_object.id
  and preservation_object.preserved_object.id = file_set.id
  and file_set.id in ( select member_ids from scanned_resource where id = 'XYZ' )
```

**Comment by tpendragon** [comment]
I added a PR for grabbing the FileSet fixity status which should perform reasonably well. I'm not totally sure what we want for the cloud fixity status, but I have this gnarly thing which gets all the events' latest statuses for every deep child file set for every attached checked node. It takes ~260ms for that big item, which is pretty long, but I'm not sure we need this much information.

```
        WITH RECURSIVE deep_members AS (
          select member.*
          FROM orm_resources a,
          jsonb_array_elements(a.metadata->'member_ids') AS b(member)
          JOIN orm_resources member ON (b.member->>'id')::UUID = member.id
          WHERE a.id = 'b62ebe65-7a92-4bb9-9458-a5f992571076'
          UNION
          SELECT mem.*
          FROM deep_members f,
          jsonb_array_elements(f.metadata->'member_ids') AS g(member)
          JOIN orm_resources mem ON (g.member->>'id')::UUID = mem.id
        ), deep_events AS (
          select event.metadata->'resource_id'->0->>'id' AS id, event.metadata->'child_id'->0->>'id' AS child_id, event.metadata->'status'->>0 AS status, event.updated_at
          from deep_members member
          JOIN orm_resources po ON member.id = (po.metadata->'preserved_object_id'->0->>'id')::UUID
          JOIN orm_resources event ON po.id = (event.metadata->'resource_id'->0->>'id')::UUID
          WHERE member.internal_resource = 'FileSet'
          AND po.internal_resource = 'PreservationObject'
          AND event.internal_resource = 'Event'
        )
        select deep_events.* FROM (
          select id, child_id, MAX(event.updated_at) AS updated_at FROM deep_events event
          GROUP BY id, child_id
        ) AS latest_events
        INNER JOIN deep_events
        ON deep_events.id = latest_events.id
        AND deep_events.updated_at = latest_events.updated_at
        AND deep_events.child_id = latest_events.child_id
```

**Comment by tpendragon** [comment]
The above query returns something like this:

```
                  id                  |               child_id               | status  |         updated_at
--------------------------------------+--------------------------------------+---------+----------------------------
 68ebf9e3-2984-42b2-a682-74570f21fa79 | c717f9b3-dcd9-4d41-aa2c-a9c5e4ca6714 | SUCCESS | 2019-04-25 23:10:51.485432
 68ebf9e3-2984-42b2-a682-74570f21fa79 | d2c23123-8229-492b-8c72-a1002ff5abac | FAILURE | 2019-04-25 23:10:50.302524
 7a3b97d2-3911-4a28-9357-db8a7987ae02 | cbf0f891-63cc-4aec-bdbc-9950ac2d2159 | SUCCESS | 2019-04-25 23:10:50.490057
 7a3b97d2-3911-4a28-9357-db8a7987ae02 | f7cb14e5-528d-4763-8692-d08c58be0419 | SUCCESS | 2019-04-25 23:10:51.965664
 92ca6a80-960c-4cbf-bb4c-20d458d20069 | 49401530-2301-42a6-ad71-21aedf356b53 | SUCCESS | 2019-04-25 23:10:52.073107
 92ca6a80-960c-4cbf-bb4c-20d458d20069 | 4a428597-0235-4f77-b0b8-8e89366d3a61 | SUCCESS | 2019-04-25 23:10:52.06533
```

**Comment by escowles** [comment]
If the simpler/faster query would handle MVWs with child volumes that have child FileSets, then I think that is fine.  We have talked about deeper nesting and may want to do that in the future, but we haven't needed to do it yet.

**Comment by tpendragon** [comment]
@escowles Why does it show cloud fixity as per-FileSet? There's a PreservationObject per FileSet, but an Event per file

**Comment by escowles** [comment]
@tpendragon Oh, I think I misunderstood that.  At this point, I think I might just take out the cloud fixity to get this merged faster, and leave cloud fixity for a separate PR.

**Pull request merged**
